CREATE TABLE champions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    image_url VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    best_time INT DEFAULT NULL ,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    time_taken INT NOT NULL,
    played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


INSERT INTO users (id, username, email, password, is_admin)
VALUES
(1, "Pepe", "pepe@gmail.com", "123", true),
(2, "Pepe2", "pepe2@gmail.com", "123", false);

INSERT INTO scores (user_id, time_taken)
VALUES
(1, 10),
(1, 20),
(1, 30),
(2, 10),
(2, 20),
(2, 30);
INSERT INTO champions (name, image_url)
VALUES
('Aatrox', 'https://guesschamp.com/lol/aatrox.jpg'),
('Ahri', 'https://guesschamp.com/lol/ahri.jpg'),
('Akali', 'https://guesschamp.com/lol/akali.jpg'),
('Akshan', 'https://guesschamp.com/lol/akshan.jpg'),
('Alistar', 'https://guesschamp.com/lol/alistar.jpg'),
('Ambessa', 'https://guesschamp.com/lol/ambessa.jpg'),
('Amumu', 'https://guesschamp.com/lol/amumu.jpg'),
('Anivia', 'https://guesschamp.com/lol/anivia.jpg'),
('Annie', 'https://guesschamp.com/lol/annie.jpg'),
('Aphelios', 'https://guesschamp.com/lol/aphelios.jpg'),
('Ashe', 'https://guesschamp.com/lol/ashe.jpg'),
('Aurelion Sol', 'https://guesschamp.com/lol/aurelionsol.jpg'),
('Aurora', 'https://guesschamp.com/lol/aurora.jpg'),
('Azir', 'https://guesschamp.com/lol/azir.jpg'),
('Bard', 'https://guesschamp.com/lol/bard.jpg'),
('Bel\'Veth', 'https://guesschamp.com/lol/belveth.jpg'),
('Blitzcrank', 'https://guesschamp.com/lol/blitzcrank.jpg'),
('Brand', 'https://guesschamp.com/lol/brand.jpg'),
('Braum', 'https://guesschamp.com/lol/braum.jpg'),
('Briar', 'https://guesschamp.com/lol/briar.jpg'),
('Caitlyn', 'https://guesschamp.com/lol/caitlyn.jpg'),
('Camille', 'https://guesschamp.com/lol/camille.jpg'),
('Cassiopeia', 'https://guesschamp.com/lol/cassiopeia.jpg'),
('Cho\'Gath', 'https://guesschamp.com/lol/chogath.jpg'),
('Corki', 'https://guesschamp.com/lol/corki.jpg'),
('Darius', 'https://guesschamp.com/lol/darius.jpg'),
('Diana', 'https://guesschamp.com/lol/diana.jpg'),
('Dr. Mundo', 'https://guesschamp.com/lol/drmundo.jpg'),
('Draven', 'https://guesschamp.com/lol/draven.jpg'),
('Ekko', 'https://guesschamp.com/lol/ekko.jpg'),
('Elise', 'https://guesschamp.com/lol/elise.jpg'),
('Evelynn', 'https://guesschamp.com/lol/evelynn.jpg'),
('Ezreal', 'https://guesschamp.com/lol/ezreal.jpg'),
('Fiddlesticks', 'https://guesschamp.com/lol/fiddlesticks.jpg'),
('Fiora', 'https://guesschamp.com/lol/fiora.jpg'),
('Fizz', 'https://guesschamp.com/lol/fizz.jpg'),
('Galio', 'https://guesschamp.com/lol/galio.jpg'),
('Gangplank', 'https://guesschamp.com/lol/gangplank.jpg'),
('Garen', 'https://guesschamp.com/lol/garen.jpg'),
('Gnar', 'https://guesschamp.com/lol/gnar.jpg'),
('Gragas', 'https://guesschamp.com/lol/gragas.jpg'),
('Graves', 'https://guesschamp.com/lol/graves.jpg'),
('Gwen', 'https://guesschamp.com/lol/gwen.jpg'),
('Hecarim', 'https://guesschamp.com/lol/hecarim.jpg'),
('Heimerdinger', 'https://guesschamp.com/lol/heimerdinger.jpg'),
('Hwei', 'https://guesschamp.com/lol/hwei.jpg'),
('Illaoi', 'https://guesschamp.com/lol/illaoi.jpg'),
('Irelia', 'https://guesschamp.com/lol/irelia.jpg'),
('Ivern', 'https://guesschamp.com/lol/ivern.jpg'),
('Janna', 'https://guesschamp.com/lol/janna.jpg'),
('Jarvan IV', 'https://guesschamp.com/lol/jarvanIV.jpg'),
('Jax', 'https://guesschamp.com/lol/jax.jpg'),
('Jayce', 'https://guesschamp.com/lol/jayce.jpg'),
('Jhin', 'https://guesschamp.com/lol/jhin.jpg'),
('Jinx', 'https://guesschamp.com/lol/jinx.jpg'),
('K\'sante', 'https://guesschamp.com/lol/ksante.jpg'),
('Kai\'Sa', 'https://guesschamp.com/lol/kaisa.jpg'),
('Kalista', 'https://guesschamp.com/lol/kalista.jpg'),
('Karma', 'https://guesschamp.com/lol/karma.jpg'),
('Karthus', 'https://guesschamp.com/lol/karthus.jpg'),
('Kassadin', 'https://guesschamp.com/lol/kassadin.jpg'),
('Katarina', 'https://guesschamp.com/lol/katarina.jpg'),
('Kayle', 'https://guesschamp.com/lol/kayle.jpg'),
('Kayn', 'https://guesschamp.com/lol/kayn.jpg'),
('Kennen', 'https://guesschamp.com/lol/kennen.jpg'),
('Kha\'Zix', 'https://guesschamp.com/lol/khazix.jpg'),
('Kindred', 'https://guesschamp.com/lol/kindred.jpg'),
('Kled', 'https://guesschamp.com/lol/kled.jpg'),
('Kog\'Maw', 'https://guesschamp.com/lol/kogMaw.jpg'),
('LeBlanc', 'https://guesschamp.com/lol/leblanc.jpg'),
('Lee Sin', 'https://guesschamp.com/lol/leeSin.jpg'),
('Leona', 'https://guesschamp.com/lol/leona.jpg'),
('Lillia', 'https://guesschamp.com/lol/lillia.jpg'),
('Lissandra', 'https://guesschamp.com/lol/lissandra.jpg'),
('Lucian', 'https://guesschamp.com/lol/lucian.jpg'),
('Lulu', 'https://guesschamp.com/lol/lulu.jpg'),
('Lux', 'https://guesschamp.com/lol/lux.jpg'),
('Malphite', 'https://guesschamp.com/lol/malphite.jpg'),
('Malzahar', 'https://guesschamp.com/lol/malzahar.jpg'),
('Maokai', 'https://guesschamp.com/lol/maokai.jpg'),
('Master Yi', 'https://guesschamp.com/lol/masterYi.jpg'),
('Mel', 'https://guesschamp.com/lol/mel.jpg'),
('Milio', 'https://guesschamp.com/lol/milio.jpg'),
('Miss Fortune', 'https://guesschamp.com/lol/missFortune.jpg'),
('Mordekaiser', 'https://guesschamp.com/lol/mordekaiser.jpg'),
('Morgana', 'https://guesschamp.com/lol/morgana.jpg'),
('Naafiri', 'https://guesschamp.com/lol/naafiri.jpg'),
('Nami', 'https://guesschamp.com/lol/nami.jpg'),
('Nasus', 'https://guesschamp.com/lol/nasus.jpg'),
('Nautilus', 'https://guesschamp.com/lol/nautilus.jpg'),
('Neeko', 'https://guesschamp.com/lol/neeko.jpg'),
('Nidalee', 'https://guesschamp.com/lol/nidalee.jpg'),
('Nilah', 'https://guesschamp.com/lol/nilah.jpg'),
('Nocturne', 'https://guesschamp.com/lol/nocturne.jpg'),
('Nunu and Willump', 'https://guesschamp.com/lol/nunuwillump.jpg'),
('Olaf', 'https://guesschamp.com/lol/olaf.jpg'),
('Orianna', 'https://guesschamp.com/lol/orianna.jpg'),
('Ornn', 'https://guesschamp.com/lol/ornn.jpg'),
('Pantheon', 'https://guesschamp.com/lol/pantheon.jpg'),
('Poppy', 'https://guesschamp.com/lol/poppy.jpg'),
('Pyke', 'https://guesschamp.com/lol/pyke.jpg'),
('Qiyana', 'https://guesschamp.com/lol/qiyana.jpg'),
('Quinn', 'https://guesschamp.com/lol/quinn.jpg'),
('Rakan', 'https://guesschamp.com/lol/rakan.jpg'),
('Rammus', 'https://guesschamp.com/lol/rammus.jpg'),
('Rek\'Sai', 'https://guesschamp.com/lol/reksai.jpg'),
('Rell', 'https://guesschamp.com/lol/rell.jpg'),
('Renata', 'https://guesschamp.com/lol/renata.jpg'),
('Renekton', 'https://guesschamp.com/lol/renekton.jpg'),
('Rengar', 'https://guesschamp.com/lol/rengar.jpg'),
('Riven', 'https://guesschamp.com/lol/riven.jpg'),
('Rumble', 'https://guesschamp.com/lol/rumble.jpg'),
('Ryze', 'https://guesschamp.com/lol/ryze.jpg'),
('Samira', 'https://guesschamp.com/lol/samira.jpg'),
('Sejuani', 'https://guesschamp.com/lol/sejuani.jpg'),
('Senna', 'https://guesschamp.com/lol/senna.jpg'),
('Seraphine', 'https://guesschamp.com/lol/seraphine.jpg'),
('Sett', 'https://guesschamp.com/lol/sett.jpg'),
('Shaco', 'https://guesschamp.com/lol/shaco.jpg'),
('Shen', 'https://guesschamp.com/lol/shen.jpg'),
('Shyvana', 'https://guesschamp.com/lol/shyvana.jpg'),
('Singed', 'https://guesschamp.com/lol/singed.jpg'),
('Sion', 'https://guesschamp.com/lol/sion.jpg'),
('Sivir', 'https://guesschamp.com/lol/sivir.jpg'),
('Skarner', 'https://guesschamp.com/lol/skarner.jpg'),
('Smolder', 'https://guesschamp.com/lol/smolder.jpg'),
('Sona', 'https://guesschamp.com/lol/sona.jpg'),
('Soraka', 'https://guesschamp.com/lol/soraka.jpg'),
('Swain', 'https://guesschamp.com/lol/swain.jpg'),
('Sylas', 'https://guesschamp.com/lol/sylas.jpg'),
('Syndra', 'https://guesschamp.com/lol/syndra.jpg'),
('Tahm Kench', 'https://guesschamp.com/lol/tahmkench.jpg'),
('Taliyah', 'https://guesschamp.com/lol/taliyah.jpg'),
('Talon', 'https://guesschamp.com/lol/talon.jpg'),
('Taric', 'https://guesschamp.com/lol/taric.jpg'),
('Teemo', 'https://guesschamp.com/lol/teemo.jpg'),
('Thresh', 'https://guesschamp.com/lol/thresh.jpg'),
('Tristana', 'https://guesschamp.com/lol/tristana.jpg'),
('Trundle', 'https://guesschamp.com/lol/trundle.jpg'),
('Tryndamere', 'https://guesschamp.com/lol/tryndamere.jpg'),
('Twisted Fate', 'https://guesschamp.com/lol/twistedfate.jpg'),
('Twitch', 'https://guesschamp.com/lol/twitch.jpg'),
('Udyr', 'https://guesschamp.com/lol/udyr.jpg'),
('Urgot', 'https://guesschamp.com/lol/urgot.jpg'),
('Varus', 'https://guesschamp.com/lol/varus.jpg'),
('Vayne', 'https://guesschamp.com/lol/vayne.jpg'),
('Veigar', 'https://guesschamp.com/lol/veigar.jpg'),
('Vel\'Koz', 'https://guesschamp.com/lol/velkoz.jpg'),
('Vex', 'https://guesschamp.com/lol/vex.jpg'),
('Vi', 'https://guesschamp.com/lol/vi.jpg'),
('Viego', 'https://guesschamp.com/lol/viego.jpg'),
('Viktor', 'https://guesschamp.com/lol/viktor.jpg'),
('Vladimir', 'https://guesschamp.com/lol/vladimir.jpg'),
('Volibear', 'https://guesschamp.com/lol/volibear.jpg'),
('Warwick', 'https://guesschamp.com/lol/warwick.jpg'),
('Wukong', 'https://guesschamp.com/lol/wukong.jpg'),
('Xayah', 'https://guesschamp.com/lol/xayah.jpg'),
('Xerath', 'https://guesschamp.com/lol/xerath.jpg'),
('Xin Zhao', 'https://guesschamp.com/lol/xinzhao.jpg'),
('Yasuo', 'https://guesschamp.com/lol/yasuo.jpg'),
('Yone', 'https://guesschamp.com/lol/yone.jpg'),
('Yorick', 'https://guesschamp.com/lol/yorick.jpg'),
('Yuumi', 'https://guesschamp.com/lol/yuumi.jpg'),
('Zac', 'https://guesschamp.com/lol/zac.jpg'),
('Zed', 'https://guesschamp.com/lol/zed.jpg'),
('Zeri', 'https://guesschamp.com/lol/zeri.jpg'),
('Ziggs', 'https://guesschamp.com/lol/ziggs.jpg'),
('Zilean', 'https://guesschamp.com/lol/zilean.jpg'),
('Zoe', 'https://guesschamp.com/lol/zoe.jpg'),
('Zyra', 'https://guesschamp.com/lol/zyra.jpg');